### ISSUE TITLE
Have you tried to generate the localization cues by yourself

### ISSUE THREAD

**Issue by yaoqi-zd** [xtudbxk/SEC-tensorflow#1]
Have you tried to generate the localization cues by yourself ? I mean, to train a multi label classification network and generate the initial seeds using CAM

**Comment by xtudbxk** [comment]
Sorry for the late reply.
Yes, I did. But the result is a little lower than using the offered seed. The miou is about 0.48. If you want to generate the seed by yourself, you can refer to the project https://github.com/speedinghzl/DSRG which offers the network to generate a better seed.
By the way, if you are interested in the DSRG project, I also offered a tensorflow version for it which is at https://github.com/xtudbxk/DSRG-tensorflow.

**Comment by yaoqi-zd** [comment]
Hi, thanks for your reply, my segmentation performance is also lower than that reported in SEC paper with my own generated seed. I'll continue to try anyway

**Comment by XZNWU** [comment]
Have you tried to generate the localization cues by yourself ? Can you share the code? @yaoqi-zd

**Comment by yaoqi-zd** [comment]
@xiangzhang06 No, I give up reproducing the initial seeds

**Comment by Hukongtao** [comment]
How do you generate your own  localization cues? Because I need to try this method with my own data. Can you share the code?

**Comment by Hukongtao** [comment]
@yaoqi-zd How do you generate your own localization cues? Because I need to try this method with my own data. Can you share the code?

**Comment by yaoqi-zd** [comment]
@Hukongtao sorry, I cannot produce the initial seed with good quality by myself, I just put this task aside
