### ISSUE TITLE
Trained Model, Please

### ISSUE THREAD

**Issue by terenceylchow124** [xtudbxk/SEC-tensorflow#11]
Thanks for the tensorflow of SEC! I did the training, but the predicted image were all black images. I guess there might be something wrong of my dataset. Therefore, it would be helpful if you could provide the trained model also?

**Comment by xtudbxk** [comment]
It seems I didn't keep the trained model now. And in my experience, you can adjust the lr smaller to avoid the problem. What's more, please remember to convert your dataset using the convert.py under "data" folder.

**Comment by terenceylchow124** [comment]
I did the procedure again for converting the dataset, and put it under "/data". 
This time, I tried the evaluation code deeplab_aspp_test.py, but I though the create_network function went wrong since there were no "fc_1", "fc_2", "fc_3" and "fc_4". Even though I fixed this, the code still gave me error message: 

![image](https://user-images.githubusercontent.com/68972473/92831646-a3696180-f3a4-11ea-8c56-e43a6d5c3895.png)

the error happened from: 

![image](https://user-images.githubusercontent.com/68972473/92831756-cd228880-f3a4-11ea-9ea5-d868e9d44605.png)

I guessed maybe something in dataset.py went wrong, but still couldn't find.

**Comment by terenceylchow124** [comment]
> Thanks for the tensorflow of SEC! I did the training, but the predicted image were all black images. I guess there might be something wrong of my dataset. Therefore, it would be helpful if you could provide the trained model also?

I made it wrong, it should another repository, "DSRG-tensorflow". I trained the model again, and the result was very reliable which is comparable with the image predicted by the given pretrained model. But the "SEC-tensorflow" still faces some bugs in evaluation part which mentioned above.

**Comment by xtudbxk** [comment]
Sorry for the late reply. The origin file "deeplab_aspp_test.py" is prepared for the deeplab-assp network while SEC uses the deeplab network. So you can modify the build function of evaluation code following [SEC.py](https://github.com/xtudbxk/SEC-tensorflow/blob/master/SEC.py}. The error you reported seems that the output of network has a error type, and it most probably related to the building network structure in build function. So I couldn't find the reason without the modifed code you did.

**Comment by xtudbxk** [comment]
reopen if any question~
