### ISSUE TITLE
Segmentation fault with pydensecrf

### ISSUE THREAD

**Issue by FuyaLuo** [xtudbxk/SEC-tensorflow#3]
Hi,

I am trying to install the pydensecrf module with pip install. The library seemed to be installed successfully since it can import normally. My tensorflow version is gpu-1.5. But when I tried to run "python SEC.py 0", it get a segmentation fault. I used "gdb python" to locate error is in "pydensecrf/densecrf/src/permutohedral.cpp: 255 : No such files".

I would really appreciate if anyone could help me with this.

**Comment by xtudbxk** [comment]
The problem seems to be related with the installation of pydensecrf, and from the page of the probject of [pydensecrf](https://github.com/lucasb-eyer/pydensecrf). I think maybe you can update your cython lib to a newer version, and then resintall the pydensecrf.

**Comment by xtudbxk** [comment]
Dose the solution solve your problem? Should I close this issue?

**Comment by FlorianLuo** [comment]
Thanks for your reply. I have tried to update the cython lib and reinstall the pydensecrf, but I still get the same error. My cython version is 0.28.5.

**Comment by FuyaLuo** [comment]
Thanks for your reply. I have tried to update the cython lib and reinstall the pydensecrf, but I still get the same error. My cython version is 0.28.5.

**Comment by xtudbxk** [comment]
A other reason I can think is that maybe you didn't install the cython. Just type "apt install cython" to see if the problem solved.

**Comment by FuyaLuo** [comment]
I have already installed cython, and its version is 0.28.5. I solve the problem by uninstalling the pydensecrf module, and instaling krahenbuhl2013 like SEC-caffe to replace it. Then, I make some change in code. Thanks for your advice, and you can close this issue. 
By the way, could you please provide the websites of the file "SegmentationClassAug"? Since the official VOC2012 dataset don't provide this file.

**Comment by xtudbxk** [comment]
Glad to hear that. The extra dataset is the [SDS](http://home.bharathh.info/pubs/codes/SBD/download.html).

**Comment by FuyaLuo** [comment]
Thanks.

**Comment by yezifeiafei** [comment]
@FlorianLuo  Hi, I seem to meet the same problem.  How did you solve it?

**Comment by FuyaLuo** [comment]
@yezifeiafei  I solve the problem by uninstalling the pydensecrf module, and instaling krahenbuhl2013 like [SEC-caffe](https://github.com/kolesman/SEC) to replace it. Then, I make some change in code.
