### ISSUE TITLE
Segmentation fault (core dumped) on self.sess.run(self.net["accum_gradient_accum"], feed_dict=params)

### ISSUE THREAD

**Issue by yezifeiafei** [xtudbxk/SEC-tensorflow#6]
Thanks for the wonderful work.

I'm trying to execute the Python script, but I am getting the following error:

```
$ python SEC.py 1
len:{'train': 10582}
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:84:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
load init model success: ./model/init.npy
start_time: 1543842539.624039
config -- lr:0.001000 weight_decay:0.000050 momentum:0.900000 batch_size:4.000000 epoches:30.000000
Segmentation fault (core dumped)
```

I'm using python 2.7.13 and TensorFlow 1.4.1.

Can someone tell me why this happens, and how can I solve?

**Comment by xtudbxk** [comment]
I use python3, and I just think maybe you should use python3 and reinstall the pydensecrf. This errors seems from the cython code for the crf inference which is supported by the pydensecrf lib.
