### ISSUE TITLE
"model_path":"./20180622-3-4/final-0",

### ISSUE THREAD

**Issue by Hukongtao** [xtudbxk/SEC-tensorflow#8]
I didn't find the model in your Evaluation project.

**Comment by xtudbxk** [comment]
The evaluation project is for all the project of mine. So maybe you need to adjust a little for one specified project. Generally speaking, the create_network and the get_weights_and_bias are the main two functions to change.

**Comment by Hukongtao** [comment]
@xtudbxk 好的好的。您是华科的吧？放不方便加下大神的QQ或微信啊。或者你加我。QQ：1821141394

**Comment by xtudbxk** [comment]
Ok, I just added you. And Now, I just closed the issue.
