### ISSUE TITLE
the Training Net work and the Test Network

### ISSUE THREAD

**Issue by Hukongtao** [xtudbxk/SEC-tensorflow#9]
Are the Training Net work and the Test Network different? I can't restore the norm-38999

**Comment by xtudbxk** [comment]
Only a few differences. For SEC, you need just remove the ASPP strcture in the deeplab_aspp_test.py.  From my view, the only two different function is in create_network and get_weights_and_bias.

**Comment by xtudbxk** [comment]
If the solution works or not, please tell me. Thanks ~
